# gdalmanage
# Autogenerated from man page /usr/share/man/man1/gdalmanage.1.gz
complete -c gdalmanage -s r -d 'Recursively scan files/folders for raster files. UNINDENT NDENT 0. 0'
complete -c gdalmanage -s u -d 'Report failures if file type is unidentified. UNINDENT NDENT 0. 0'
complete -c gdalmanage -s f -d 'Specify format of raster file if unknown by the application'

