# gdal_polygonize
# Autogenerated from man page /usr/share/man/man1/gdal_polygonize.1.gz
complete -c gdal_polygonize -s 8 -d 'Use 8 connectedness.  Default is 4 connectedness. UNINDENT NDENT 0. 0'
complete -c gdal_polygonize -o nomask -d 'Do not use the default validity mask for the input band (such as nodata, or a…'
complete -c gdal_polygonize -o mask -d 'Use the first band of the specified file as a validity mask (zero is invalid,…'
complete -c gdal_polygonize -s b -d 'The band on <raster_file> to build the polygons from.  Starting with GDAL 2'
complete -c gdal_polygonize -s f -d 'Select the output format.  Starting with GDAL 2'
complete -c gdal_polygonize -s q -d 'The script runs in quiet mode'

