# gdal_create
# Autogenerated from man page /usr/share/man/man1/gdal_create.1.gz
complete -c gdal_create -o ot -d 'Force the output image bands to have a specific data type supported by the dr…'
complete -c gdal_create -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c gdal_create -o outsize -d 'Set the size of the output file in pixels.  First figure is width'
complete -c gdal_create -o bands -d 'Number of bands.  Defaults to 1 if -outsize is specified, or 0 otherwise'
complete -c gdal_create -o burn -d 'A fixed value to burn into a band for all objects'
complete -c gdal_create -o a_srs -d 'Override the projection for the output file'
complete -c gdal_create -o a_ullr -d 'Assign the georeferenced bounds of the output file. UNINDENT NDENT 0. 0'
complete -c gdal_create -o a_nodata -d 'Assign a specified nodata value to output bands. UNINDENT NDENT 0. 0'
complete -c gdal_create -o mo -d 'Passes a metadata key and value to set on the output dataset if possible'
complete -c gdal_create -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdal_create -s q -d 'Suppress progress monitor and other non-error output. UNINDENT NDENT 0. 0'
complete -c gdal_create -o if -d 'New in version 3. 3'

