# gdalmdimtranslate
# Autogenerated from man page /usr/share/man/man1/gdalmdimtranslate.1.gz
complete -c gdalmdimtranslate -o if -d 'Format/driver name to be attempted to open the input file(s)'
complete -c gdalmdimtranslate -o of -d 'Select the output format'
complete -c gdalmdimtranslate -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdalmdimtranslate -o array -d 'Instead of converting the whole dataset, select one array, and possibly perfo…'
complete -c gdalmdimtranslate -o group -d 'Instead of converting the whole dataset, select one group, and possibly perfo…'
complete -c gdalmdimtranslate -o subset -d 'Performs a subsetting (trimming or slicing) operation along a dimension, prov…'
complete -c gdalmdimtranslate -o scaleaxes -d 'Applies a integral scale factor to one or several dimensions, that is extract…'
complete -c gdalmdimtranslate -o oo -d 'New in version 3. 4. sp Source dataset open option (format specific) '

