# gdal_pansharpen
# Autogenerated from man page /usr/share/man/man1/gdal_pansharpen.1.gz
complete -c gdal_pansharpen -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c gdal_pansharpen -s b -d 'Select band band from the input spectral bands for output'
complete -c gdal_pansharpen -s w -d 'Specify a weight for the computation of the pseudo panchromatic value'
complete -c gdal_pansharpen -s r -d 'Select a resampling algorithm. UNINDENT NDENT 0. 0'
complete -c gdal_pansharpen -o threads -d 'Specify number of threads to use to do the resampling and pan-sharpening itse…'
complete -c gdal_pansharpen -o bitdepth -d 'Specify the bit depth of the panchromatic and spectral bands (e. g.  12)'
complete -c gdal_pansharpen -o nodata -d 'Specify nodata value for bands'
complete -c gdal_pansharpen -o spat_adjust -d 'Select behavior when bands have not the same extent'
complete -c gdal_pansharpen -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdal_pansharpen -s q -d 'Suppress progress monitor and other non-error output. UNINDENT NDENT 0. 0'

