# gdalsrsinfo
# Autogenerated from man page /usr/share/man/man1/gdalsrsinfo.1.gz
complete -c gdalsrsinfo -l single-line -d 'Print WKT on single line . UNINDENT NDENT 0. 0'
complete -c gdalsrsinfo -s V -d 'Validate SRS . UNINDENT NDENT 0. 0'
complete -c gdalsrsinfo -s e -d 'Search for EPSG number(s) corresponding to SRS . UNINDENT NDENT 0. 0'
complete -c gdalsrsinfo -s o -d 'Output types: NDENT 7'

