# gdallocationinfo
# Autogenerated from man page /usr/share/man/man1/gdallocationinfo.1.gz
complete -c gdallocationinfo -o xml -d 'The output report will be XML formatted for convenient post processing'
complete -c gdallocationinfo -o lifonly -d 'The only output is filenames production from the LocationInfo request against…'
complete -c gdallocationinfo -o valonly -d 'The only output is the pixel values of the selected pixel on each of the sele…'
complete -c gdallocationinfo -s b -d 'Selects a band to query.   Multiple bands can be listed'
complete -c gdallocationinfo -o overview -d 'Query the (overview_level)th overview (overview_level=1 is the 1st overview),…'
complete -c gdallocationinfo -o l_srs -d 'The coordinate system of the input x, y location. UNINDENT NDENT 0. 0'
complete -c gdallocationinfo -o geoloc -d 'Indicates input x,y points are in the georeferencing system of the image'
complete -c gdallocationinfo -o wgs84 -d 'Indicates input x,y points are WGS84 long, lat. UNINDENT NDENT 0. 0'
complete -c gdallocationinfo -o oo -d 'Dataset open option (format specific) . UNINDENT NDENT 0. 0'

