# gdaltransform
# Autogenerated from man page /usr/share/man/man1/gdaltransform.1.gz
complete -c gdaltransform -o s_srs -d 'Set source spatial reference'
complete -c gdaltransform -o t_srs -d 'set target spatial reference'
complete -c gdaltransform -o ct -d 'A PROJ string (single step operation or multiple step string starting with +p…'
complete -c gdaltransform -o to -d 'set a transformer option suitable to pass to \\%GDALCreateGenImgProjTransforme…'
complete -c gdaltransform -o order -d 'order of polynomial used for warping (1 to 3)'
complete -c gdaltransform -o tps -d 'Force use of thin plate spline transformer based on available GCPs'
complete -c gdaltransform -o rpc -d 'Force use of RPCs. UNINDENT NDENT 0. 0'
complete -c gdaltransform -o geoloc -d 'Force use of Geolocation Arrays. UNINDENT NDENT 0. 0'
complete -c gdaltransform -s i -d 'Inverse transformation: from destination to source. UNINDENT NDENT 0. 0'
complete -c gdaltransform -o gcp -d 'Provide a GCP to be used for transformation (generally three or more are requ…'
complete -c gdaltransform -o output_xy -d 'Restrict output to "x y" instead of "x y z" . UNINDENT NDENT 0. 0'

