# gdal_merge
# Autogenerated from man page /usr/share/man/man1/gdal_merge.1.gz
complete -c gdal_merge -s o -d 'The name of the output file, which will be created if it does not already exi…'
complete -c gdal_merge -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c gdal_merge -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdal_merge -o ot -d 'Force the output image bands to have a specific data type supported by the dr…'
complete -c gdal_merge -o ps -d 'Pixel size to be used for the output file'
complete -c gdal_merge -o tap -d '(target aligned pixels) align the coordinates of the extent of the output fil…'
complete -c gdal_merge -o ul_lr -d 'The extents of the output file'
complete -c gdal_merge -s v -d 'Generate verbose output of mosaicing operations as they are done'
complete -c gdal_merge -o separate -d 'Place each input file into a separate band. UNINDENT NDENT 0. 0'
complete -c gdal_merge -o pct -d 'Grab a pseudo-color table from the first input image, and use it for the outp…'
complete -c gdal_merge -s n -d 'Ignore pixels from files being merged in with this pixel value'
complete -c gdal_merge -o a_nodata -d 'Assign a specified nodata value to output bands. UNINDENT NDENT 0. 0'
complete -c gdal_merge -o init -d 'Pre-initialize the output image bands with these values'
complete -c gdal_merge -o createonly -d 'The output file is created (and potentially pre-initialized) but no input ima…'

