# gdaladdo
# Autogenerated from man page /usr/share/man/man1/gdaladdo.1.gz
complete -c gdaladdo -s r -d 'Select a resampling algorithm'
complete -c gdaladdo -s b -d 'Select an input band band for overview generation'
complete -c gdaladdo -o ro -d 'open the dataset in read-only mode, in order to generate external overview (f…'
complete -c gdaladdo -o clean -d 'remove all overviews. UNINDENT NDENT 0. 0'
complete -c gdaladdo -o oo -d 'Dataset open option (format specific) . UNINDENT NDENT 0. 0'
complete -c gdaladdo -o minsize -d 'Maximum width or height of the smallest overview level'
complete -c gdaladdo -l config

