# gdal_viewshed
# Autogenerated from man page /usr/share/man/man1/gdal_viewshed.1.gz
complete -c gdal_viewshed -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdal_viewshed -s b -d 'Select an input band band containing the DEM data.  Bands are numbered from 1'
complete -c gdal_viewshed -o a_nodata -d 'The value to be set for the cells in the output raster that have no data'
complete -c gdal_viewshed -o ox -d 'The X position of the observer (in SRS units). UNINDENT NDENT 0. 0'
complete -c gdal_viewshed -o oy -d 'The Y position of the observer (in SRS units). UNINDENT NDENT 0. 0'
complete -c gdal_viewshed -o oz -d 'The height of the observer above the DEM surface in the height unit of the DEM'
complete -c gdal_viewshed -o tz -d 'The height of the target above the DEM surface in the height unit of the DEM'
complete -c gdal_viewshed -o md -d 'Maximum distance from observer to compute visibiliy'
complete -c gdal_viewshed -o cc -d 'Coefficient to consider the effect of the curvature and refraction'
complete -c gdal_viewshed -o iv -d 'Pixel value to set for invisible areas.  Default: 0 . UNINDENT NDENT 0. 0'
complete -c gdal_viewshed -o ov -d 'Pixel value to set for the cells that fall outside of the range specified by …'
complete -c gdal_viewshed -o vv -d 'Pixel value to set for visible areas.  Default: 255 . UNINDENT NDENT 0. 0'
complete -c gdal_viewshed -o om -d 'Sets what information the output contains'

