# gdalmove
# Autogenerated from man page /usr/share/man/man1/gdalmove.1.gz
complete -c gdalmove -o s_srs -d 'Override the coordinate system of the file with the indicated coordinate syst…'
complete -c gdalmove -o t_srs -d 'Defines the target coordinate system'
complete -c gdalmove -o et -d 'The error threshold (in pixels) beyond which the file will not be updated'

