# gdal_fillnodata
# Autogenerated from man page /usr/share/man/man1/gdal_fillnodata.1.gz
complete -c gdal_fillnodata -s q -d 'The script runs in quiet mode'
complete -c gdal_fillnodata -o md -d 'The maximum distance (in pixels) that the algorithm will search out for value…'
complete -c gdal_fillnodata -o si -d 'The number of 3x3 average filter smoothing iterations to run after the interp…'
complete -c gdal_fillnodata -s o -d 'Specify a special argument to the algorithm.  Currently none are supported'
complete -c gdal_fillnodata -s b -d 'The band to operate on, by default the first band is operated on'
complete -c gdal_fillnodata -o mask -d 'Use the first band of the specified file as a validity mask (zero is invalid,…'
complete -c gdal_fillnodata -o of -d 'Select the output format.  The default is %GTiff -- GeoTIFF File Format'

