# gdalmdiminfo
# Autogenerated from man page /usr/share/man/man1/gdalmdiminfo.1.gz
complete -c gdalmdiminfo -o detailed -d 'Most verbose output.  Report attribute data types and array values'
complete -c gdalmdiminfo -o nopretty -d 'Outputs on a single line without any indentation. UNINDENT NDENT 0. 0'
complete -c gdalmdiminfo -o array -d 'Name of the array used to restrict the output to the specified array'
complete -c gdalmdiminfo -o limit -d 'Number of values in each dimension that is used to limit the display of array…'
complete -c gdalmdiminfo -o oo -d 'Dataset open option (format specific).  This option may be used several times'
complete -c gdalmdiminfo -o arrayoption -d 'Option passed to \\%GDALGroup::GetMDArrayNames() to filter reported arrays'
complete -c gdalmdiminfo -o stats -d 'Read and display image statistics'
complete -c gdalmdiminfo -o if -d 'Format/driver name to be attempted to open the input file(s)'

