# gdal_proximity
# Autogenerated from man page /usr/share/man/man1/gdal_proximity.1.gz
complete -c gdal_proximity -o srcband -d 'Identifies the band in the source file to use (default is 1)'
complete -c gdal_proximity -o dstband -d 'Identifies the band in the destination file to use (default is 1)'
complete -c gdal_proximity -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c gdal_proximity -o co -d 'Many formats have one or more optional creation options that can be used to c…'
complete -c gdal_proximity -o ot -d 'Specify a data type supported by the driver, which may be one of the followin…'
complete -c gdal_proximity -o values -d 'A list of target pixel values in the source image to be considered target pix…'
complete -c gdal_proximity -o distunits -d 'Indicate whether distances generated should be in pixel or georeferenced coor…'
complete -c gdal_proximity -o maxdist -d 'The maximum distance to be generated'
complete -c gdal_proximity -o nodata -d 'Specify a nodata value to use for the destination proximity raster'
complete -c gdal_proximity -o use_input_nodata -d 'Indicate whether nodata pixels in the input raster should be nodata in the ou…'
complete -c gdal_proximity -o fixed-buf-val -d 'Specify a value to be applied to all pixels that are within the -maxdist of t…'

