# gdaltindex
# Autogenerated from man page /usr/share/man/man1/gdaltindex.1.gz
complete -c gdaltindex -s f -d 'The OGR format of the output tile index file.  Starting with GDAL 2'
complete -c gdaltindex -o tileindex -d 'The output field name to hold the file path/location to the indexed rasters'
complete -c gdaltindex -o write_absolute_path -d 'The absolute path to the raster files is stored in the tile index file'
complete -c gdaltindex -o skip_different_projection -d 'Only files with same projection as files already inserted in the tileindex wi…'
complete -c gdaltindex -o t_srs -d 'Geometries of input files will be transformed to the desired target coordinat…'
complete -c gdaltindex -o src_srs_name -d 'The name of the field to store the SRS of each tile'
complete -c gdaltindex -o src_srs_format -d 'The format in which the SRS of each tile must be written'
complete -c gdaltindex -o lyr_name -d 'Layer name to create/append to in the output tile index file'

