# gnmanalyse
# Autogenerated from man page /usr/share/man/man1/gnmanalyse.1.gz
complete -c gnmanalyse -s d -d 'The name and path of the dataset to save the layer with resulting paths'
complete -c gnmanalyse -s f -d 'Define this to set the format of newly created dataset. UNINDENT NDENT 0. 0'
complete -c gnmanalyse -s l -d 'The name of the resulting layer'
complete -c gnmanalyse -o dsco -d 'Dataset creation option (format specific) . UNINDENT NDENT 0. 0'
complete -c gnmanalyse -o lco -d 'Layer creation option (format specific) . UNINDENT NDENT 0. 0'
complete -c gnmanalyse -o alo -d 'Algorithm option (format specific)'

