# gnmmanage
# Autogenerated from man page /usr/share/man/man1/gnmmanage.1.gz
complete -c gnmmanage -o info -d 'Different information about network: system and class layers, network metadat…'
complete -c gnmmanage -s f -d 'Output file format name. UNINDENT NDENT 7. 0'
complete -c gnmmanage -o t_srs -d 'Spatial reference input. UNINDENT NDENT 7. 0'
complete -c gnmmanage -o dsco -d 'Network creation option set as pair name=value. UNINDENT . UNINDENT NDENT 0'
complete -c gnmmanage -s l -d 'UNINDENT . sp Layer name in dataset.  If unset, 0 layer is copied'
complete -c gnmmanage -s c -d 'Cost / weight . UNINDENT NDENT 7. 0'
complete -c gnmmanage -o ic -d 'Inverse cost . UNINDENT NDENT 7. 0'
complete -c gnmmanage -o dir -d 'Direction of the edge. UNINDENT . UNINDENT NDENT 0. 0'
complete -c gnmmanage -o bl -d 'Block feature before the main operation'
complete -c gnmmanage -o unbl -d 'Unblock feature before the main operation. UNINDENT NDENT 7. 0'
complete -c gnmmanage -o unblall -d 'Unblock all blocked features before the main operation. UNINDENT '

