# jstack
# Autogenerated from man page /usr/share/man/man1/jstack.1.gz
complete -c jstack -s l -d 'The long listing option prints additional information about locks'
complete -c jstack -s h -o help -d 'Prints a help message'

