# nearblack
# Autogenerated from man page /usr/share/man/man1/nearblack.1.gz
complete -c nearblack -s o -d 'The name of the output file to be created. UNINDENT NDENT 0. 0'
complete -c nearblack -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c nearblack -o co -d 'Passes a creation option to the output format driver'
complete -c nearblack -o white -d 'Search for nearly white (255) pixels instead of nearly black pixels'
complete -c nearblack -o color -d 'Search for pixels near the specified color.  May be specified multiple times'
complete -c nearblack -o near -d 'Select how far from black, white or custom colors the pixel values can be and…'
complete -c nearblack -o nb -d 'number of non-black pixels that can be encountered before the giving up searc…'
complete -c nearblack -o setalpha -d 'Adds an alpha band if the output file is specified and the input file has 3 b…'
complete -c nearblack -o setmask -d 'Adds a mask band to the output file, or adds a mask band to the input file if…'
complete -c nearblack -s q -d 'Suppress progress monitor and other non-error output. UNINDENT NDENT 0. 0'

