# ogr_layer_algebra
# Autogenerated from man page /usr/share/man/man1/ogr_layer_algebra.1.gz
complete -c ogr_layer_algebra -o input_ds -d 'Input data set path for the operation to be performed'
complete -c ogr_layer_algebra -o input_lyr -d 'Layer name of the input_ds for which the operations have to be performed ( Op…'
complete -c ogr_layer_algebra -o method_ds -d 'Method data set path for the operation to be performed'
complete -c ogr_layer_algebra -o method_lyr -d 'Layer name of the method_ds for which the operations have to be performed ( O…'
complete -c ogr_layer_algebra -o output_ds -d 'Output data set path for writing the result of the operations performed by og…'
complete -c ogr_layer_algebra -o output_lyr_name -d 'Layer name of the output_lyr_name where the output vector has to be written'
complete -c ogr_layer_algebra -o overwrite -d 'Indicates whether the output_ds have to be overwritten with the generated res…'
complete -c ogr_layer_algebra -o opt -d 'Attributes for which the operation has to run on input_ds and method_ds '
complete -c ogr_layer_algebra -s f -d 'Select the output formatf not specified, the format is guessed from the exten…'
complete -c ogr_layer_algebra -o dsco -d 'Dataset creation option (format specific) . UNINDENT NDENT 0. 0'
complete -c ogr_layer_algebra -o lco -d 'Layer creation option (format specific) . UNINDENT NDENT 0. 0'
complete -c ogr_layer_algebra -o input_fields -d 'Comma-delimited list of fields from input layer to copy to the output layer ,…'
complete -c ogr_layer_algebra -o method_fields -d 'Comma-delimited list of fields from method layer to copy to the output layer …'
complete -c ogr_layer_algebra -o nlt -d 'Define the geometry type for the created layer'
complete -c ogr_layer_algebra -o a_srs -d 'Assign an output SRS, but without reprojecting'

