# ogrtindex
# Autogenerated from man page /usr/share/man/man1/ogrtindex.1.gz
complete -c ogrtindex -o lnum -d 'Add layer number n from each source file in the tile index. UNINDENT NDENT 0'
complete -c ogrtindex -o lname -d 'Add the layer named name from each source file in the tile index'
complete -c ogrtindex -s f -d 'Select an output format name.  The default is to create a shapefile'
complete -c ogrtindex -o tileindex -d 'The name to use for the dataset name.  Defaults to LOCATION. UNINDENT NDENT 0'
complete -c ogrtindex -o write_absolute_path -d 'Filenames are written with absolute paths . UNINDENT NDENT 0. 0'
complete -c ogrtindex -o skip_different_projection -d 'Only layers with same projection ref as layers already inserted in the tilein…'
complete -c ogrtindex -o t_srs -d 'Extent of input files will be transformed to the desired target coordinate re…'
complete -c ogrtindex -o src_srs_name -d 'The name of the field to store the SRS of each tile'
complete -c ogrtindex -o src_srs_format -d 'The format in which the SRS of each tile must be written'
complete -c ogrtindex -o accept_different_schemas -d 'By default ogrtindex checks that all layers inserted into the index have the …'

