# pct2rgb
# Autogenerated from man page /usr/share/man/man1/pct2rgb.1.gz
complete -c pct2rgb -o of -d 'Select the output format.  Starting with GDAL 2'
complete -c pct2rgb -s b -d 'Band to convert to RGB, defaults to 1. UNINDENT NDENT 0. 0'
complete -c pct2rgb -o rgba -d 'Generate a RGBA file (instead of a RGB file by default). UNINDENT NDENT 0. 0'
complete -c pct2rgb -o pct -d 'Extract the color table from <palette_file> instead of getting it from <sourc…'

