# rgb2pct
# Autogenerated from man page /usr/share/man/man1/rgb2pct.1.gz
complete -c rgb2pct -s n -d 'Select the number of colors in the generated color table.   Defaults to 256'
complete -c rgb2pct -o pct -d 'Extract the color table from <palette_file> instead of computing it'
complete -c rgb2pct -o of -d 'Select the output format.  Starting with GDAL 2'

