# sq-armor
# Autogenerated from man page /usr/share/man/man1/sq-armor.1.gz
complete -c sq-armor -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-armor -l label -d 'Selects the kind of armor header'
complete -c sq-armor -s h -l help -d 'Print help information'

