# sq-autocrypt-decode
# Autogenerated from man page /usr/share/man/man1/sq-autocrypt-decode.1.gz
complete -c sq-autocrypt-decode -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-autocrypt-decode -s B -l binary -d 'Emits binary data'
complete -c sq-autocrypt-decode -s h -l help -d 'Print help information'

