# sq-autocrypt-encode-sender
# Autogenerated from man page /usr/share/man/man1/sq-autocrypt-encode-sender.1.gz
complete -c sq-autocrypt-encode-sender -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-autocrypt-encode-sender -l email -d 'Sets the address [default: primary userid]'
complete -c sq-autocrypt-encode-sender -l prefer-encrypt -d 'Sets the prefer-encrypt attribute'
complete -c sq-autocrypt-encode-sender -s h -l help -d 'Print help information'

