# sq-certify
# Autogenerated from man page /usr/share/man/man1/sq-certify.1.gz
complete -c sq-certify -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-certify -s B -l binary -d 'Emits binary data'
complete -c sq-certify -l time -d 'Sets the certification time to TIME'
complete -c sq-certify -s d -l depth -d 'Sets the trust depth (sometimes referred to as the trust level)'
complete -c sq-certify -s a -l amount -d 'Sets the amount of trust.   Values between 1 and 120 are meaningful'
complete -c sq-certify -s r -l regex -d 'Adds a regular expression to constrain what a trusted introducer can certify'
complete -c sq-certify -s l -l local -d 'Makes the certification a local certification'
complete -c sq-certify -l non-revocable -d 'Marks the certification as being non-revocable'
complete -c sq-certify -l notation -d 'Adds a notation to the certification'
complete -c sq-certify -l expires -d 'Makes the certification expire at TIME (as ISO 8601)'
complete -c sq-certify -l expires-in -d 'Makes the certification expire after DURATION'
complete -c sq-certify -l allow-not-alive-certifier -d 'Allows the key to make a certification even if the current time is prior to i…'
complete -c sq-certify -l allow-revoked-certifier -d 'Don\\*(Aqt fail if the certificate making the certification is revoked'
complete -c sq-certify -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-certify -s h -l help -d 'Print help information'

