# sq-dearmor
# Autogenerated from man page /usr/share/man/man1/sq-dearmor.1.gz
complete -c sq-dearmor -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-dearmor -s h -l help -d 'Print help information'

