# sq-decrypt
# Autogenerated from man page /usr/share/man/man1/sq-decrypt.1.gz
complete -c sq-decrypt -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-decrypt -s n -l signatures -d 'Sets the threshold of valid signatures to N'
complete -c sq-decrypt -l signer-cert -d 'Verifies signatures with CERT'
complete -c sq-decrypt -l recipient-key -d 'Decrypts with KEY'
complete -c sq-decrypt -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-decrypt -l dump-session-key -d 'Prints the session key to stderr'
complete -c sq-decrypt -l session-key -d 'Decrypts an encrypted message using SESSION-KEY'
complete -c sq-decrypt -l dump -d 'Prints a packet dump to stderr'
complete -c sq-decrypt -s x -l hex -d 'Prints a hexdump (implies --dump)'
complete -c sq-decrypt -s h -l help -d 'Print help information'

