# sq-encrypt
# Autogenerated from man page /usr/share/man/man1/sq-encrypt.1.gz
complete -c sq-encrypt -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-encrypt -s B -l binary -d 'Emits binary data'
complete -c sq-encrypt -l recipient-cert -d 'Encrypts for all recipients in CERT-RING'
complete -c sq-encrypt -l signer-key -d 'Signs the message with KEY'
complete -c sq-encrypt -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-encrypt -s s -l symmetric -d 'Adds a password to encrypt with'
complete -c sq-encrypt -l mode -d 'Selects what kind of keys are considered for encryption'
complete -c sq-encrypt -l compression -d 'Selects compression scheme to use'
complete -c sq-encrypt -s t -l time -d 'Chooses keys valid at the specified time and sets the signature\\*(Aqs creatio…'
complete -c sq-encrypt -l use-expired-subkey -d 'If a certificate has only expired encryption-capable subkeys, falls back to u…'
complete -c sq-encrypt -s h -l help -d 'Print help information'

