# sq-inspect
# Autogenerated from man page /usr/share/man/man1/sq-inspect.1.gz
complete -c sq-inspect -l certifications -d 'Prints third-party certifications'
complete -c sq-inspect -s h -l help -d 'Print help information'

