# sq-keyserver-get
# Autogenerated from man page /usr/share/man/man1/sq-keyserver-get.1.gz
complete -c sq-keyserver-get -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-keyserver-get -s B -l binary -d 'Emits binary data'
complete -c sq-keyserver-get -s h -l help -d 'Print help information'

