# sq-keyserver
# Autogenerated from man page /usr/share/man/man1/sq-keyserver.1.gz
complete -c sq-keyserver -s p -l policy -d 'Sets the network policy to use'
complete -c sq-keyserver -s s -l server -d 'Sets the keyserver to use'
complete -c sq-keyserver -s h -l help -d 'Print help information SUBCOMMANDS'

