# sq-key-attest-certifications
# Autogenerated from man page /usr/share/man/man1/sq-key-attest-certifications.1.gz
complete -c sq-key-attest-certifications -l none -d 'Removes all prior attestations'
complete -c sq-key-attest-certifications -l all -d 'Attests to all certifications [default]'
complete -c sq-key-attest-certifications -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-attest-certifications -s B -l binary -d 'Emits binary data'
complete -c sq-key-attest-certifications -s h -l help -d 'Print help information'

