# sq-key-adopt
# Autogenerated from man page /usr/share/man/man1/sq-key-adopt.1.gz
complete -c sq-key-adopt -s r -l keyring -d 'Supplies keys for use in --key'
complete -c sq-key-adopt -s k -l key -d 'Adds the key or subkey KEY to the TARGET-KEY'
complete -c sq-key-adopt -l allow-broken-crypto -d 'Allows adopting keys from certificates using broken cryptography'
complete -c sq-key-adopt -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-adopt -s B -l binary -d 'Emits binary data'
complete -c sq-key-adopt -s h -l help -d 'Print help information'

