# sq-keyring-join
# Autogenerated from man page /usr/share/man/man1/sq-keyring-join.1.gz
complete -c sq-keyring-join -s o -l output -d 'Sets the output file to use'
complete -c sq-keyring-join -s B -l binary -d 'Don\\*(Aqt ASCII-armor the keyring'
complete -c sq-keyring-join -s h -l help -d 'Print help information'

