# sq-key-generate
# Autogenerated from man page /usr/share/man/man1/sq-key-generate.1.gz
complete -c sq-key-generate -s u -l userid -d 'Adds a userid to the key'
complete -c sq-key-generate -s c -l cipher-suite -d 'Selects the cryptographic algorithms for the key'
complete -c sq-key-generate -l with-password -d 'Protects the key with a password'
complete -c sq-key-generate -l creation-time -d 'Sets the key\\*(Aqs creation time to TIME'
complete -c sq-key-generate -l expires -d 'Makes the key expire at TIME (as ISO 8601)'
complete -c sq-key-generate -l expires-in -d 'Makes the key expire after DURATION'
complete -c sq-key-generate -l can-sign -d 'Adds a signing-capable subkey (default)'
complete -c sq-key-generate -l cannot-sign -d 'Adds no signing-capable subkey'
complete -c sq-key-generate -l can-authenticate -d 'Adds an authentication-capable subkey (default)'
complete -c sq-key-generate -l cannot-authenticate -d 'Adds no authentication-capable subkey'
complete -c sq-key-generate -l can-encrypt -d 'Adds an encryption-capable subkey'
complete -c sq-key-generate -l cannot-encrypt -d 'Adds no encryption-capable subkey'
complete -c sq-key-generate -s e -l export -d 'Writes the key to OUTFILE'
complete -c sq-key-generate -l rev-cert -d 'Writes the revocation certificate to FILE.  mandatory if OUTFILE is "-"'
complete -c sq-key-generate -s h -l help -d 'Print help information EXAMPLES  First, this generates a key  sq key generate…'

