# sq-key-userid-strip
# Autogenerated from man page /usr/share/man/man1/sq-key-userid-strip.1.gz
complete -c sq-key-userid-strip -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-userid-strip -s u -l userid -d 'The User IDs to strip.   Values must exactly match a User ID'
complete -c sq-key-userid-strip -s B -l binary -d 'Emits binary data'
complete -c sq-key-userid-strip -s h -l help -d 'Print help information'

