# sq-key-password
# Autogenerated from man page /usr/share/man/man1/sq-key-password.1.gz
complete -c sq-key-password -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-password -l clear -d 'Emit a key with unencrypted secrets'
complete -c sq-key-password -s B -l binary -d 'Emits binary data'
complete -c sq-key-password -s h -l help -d 'Print help information'

