# sq-keyring-list
# Autogenerated from man page /usr/share/man/man1/sq-keyring-list.1.gz
complete -c sq-keyring-list -l all-userids -d 'Lists all user ids, even those that are expired, revoked, or not valid under …'
complete -c sq-keyring-list -s h -l help -d 'Print help information'

