# sq-key-extract-cert
# Autogenerated from man page /usr/share/man/man1/sq-key-extract-cert.1.gz
complete -c sq-key-extract-cert -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-extract-cert -s B -l binary -d 'Emits binary data'
complete -c sq-key-extract-cert -s h -l help -d 'Print help information'

