# sq-keyring-split
# Autogenerated from man page /usr/share/man/man1/sq-keyring-split.1.gz
complete -c sq-keyring-split -s p -l prefix -d 'Writes to files with PREFIX [defaults: "FILE-" if FILE is set, or "output-" i…'
complete -c sq-keyring-split -s B -l binary -d 'Emits binary data'
complete -c sq-keyring-split -s h -l help -d 'Print help information'

