# sq-keyring-filter
# Autogenerated from man page /usr/share/man/man1/sq-keyring-filter.1.gz
complete -c sq-keyring-filter -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-keyring-filter -l userid -d 'Case-sensitively matches on the user id, requiring an exact match'
complete -c sq-keyring-filter -l name -d 'Parses user ids into name and email and case-sensitively matches on the name,…'
complete -c sq-keyring-filter -l email -d 'Parses user ids into name and email address and case-sensitively matches on t…'
complete -c sq-keyring-filter -l domain -d 'Parses user ids into name and email address and case-sensitively matches on t…'
complete -c sq-keyring-filter -l handle -d 'Matches on both primary keys and subkeys, including those certificates that m…'
complete -c sq-keyring-filter -s P -l prune-certs -d 'Removes certificate components not matching the filter'
complete -c sq-keyring-filter -s B -l binary -d 'Emits binary data'
complete -c sq-keyring-filter -l to-cert -d 'Converts any keys in the input to certificates'
complete -c sq-keyring-filter -s h -l help -d 'Print help information'

