# sq-key-userid-add
# Autogenerated from man page /usr/share/man/man1/sq-key-userid-add.1.gz
complete -c sq-key-userid-add -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-key-userid-add -s u -l userid -d 'User ID to add'
complete -c sq-key-userid-add -l creation-time -d 'Sets the creation time of this User ID\\*(Aqs binding signature to TIME'
complete -c sq-key-userid-add -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-key-userid-add -s B -l binary -d 'Emits binary data'
complete -c sq-key-userid-add -s h -l help -d 'Print help information'

