# sq-keyring-merge
# Autogenerated from man page /usr/share/man/man1/sq-keyring-merge.1.gz
complete -c sq-keyring-merge -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-keyring-merge -s B -l binary -d 'Emits binary data'
complete -c sq-keyring-merge -s h -l help -d 'Print help information'

