# sq-packet-dump
# Autogenerated from man page /usr/share/man/man1/sq-packet-dump.1.gz
complete -c sq-packet-dump -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-packet-dump -l session-key -d 'Decrypts an encrypted message using SESSION-KEY'
complete -c sq-packet-dump -l mpis -d 'Prints cryptographic artifacts'
complete -c sq-packet-dump -s x -l hex -d 'Prints a hexdump'
complete -c sq-packet-dump -s h -l help -d 'Print help information'

