# sq-packet-decrypt
# Autogenerated from man page /usr/share/man/man1/sq-packet-decrypt.1.gz
complete -c sq-packet-decrypt -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-packet-decrypt -s B -l binary -d 'Emits binary data'
complete -c sq-packet-decrypt -l recipient-key -d 'Decrypts the message with KEY'
complete -c sq-packet-decrypt -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-packet-decrypt -l session-key -d 'Decrypts an encrypted message using SESSION-KEY'
complete -c sq-packet-decrypt -l dump-session-key -d 'Prints the session key to stderr'
complete -c sq-packet-decrypt -s h -l help -d 'Print help information'

