# sq-packet-join
# Autogenerated from man page /usr/share/man/man1/sq-packet-join.1.gz
complete -c sq-packet-join -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-packet-join -l label -d 'Selects the kind of armor header'
complete -c sq-packet-join -s B -l binary -d 'Emits binary data'
complete -c sq-packet-join -s h -l help -d 'Print help information'

