# sq-packet-split
# Autogenerated from man page /usr/share/man/man1/sq-packet-split.1.gz
complete -c sq-packet-split -s p -l prefix -d 'Writes to files with PREFIX [defaults: "FILE-" if FILE is set, or "output-" i…'
complete -c sq-packet-split -s h -l help -d 'Print help information'

