# sq-revoke-userid
# Autogenerated from man page /usr/share/man/man1/sq-revoke-userid.1.gz
complete -c sq-revoke-userid -l certificate -d 'Reads the certificate to revoke from FILE or stdin, if omitted'
complete -c sq-revoke-userid -l revocation-key -d 'Signs the revocation certificate using KEY'
complete -c sq-revoke-userid -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-revoke-userid -s t -l time -d 'Chooses keys valid at the specified time and sets the revocation certificate\\…'
complete -c sq-revoke-userid -l notation -d 'Adds a notation to the certification'
complete -c sq-revoke-userid -s B -l binary -d 'Emits binary data'
complete -c sq-revoke-userid -s h -l help -d 'Print help information'

