# sq-revoke-subkey
# Autogenerated from man page /usr/share/man/man1/sq-revoke-subkey.1.gz
complete -c sq-revoke-subkey -l certificate -d 'Reads the certificate containing the subkey to revoke from FILE or stdin, if …'
complete -c sq-revoke-subkey -l revocation-key -d 'Signs the revocation certificate using KEY'
complete -c sq-revoke-subkey -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-revoke-subkey -s t -l time -d 'Chooses keys valid at the specified time and sets the revocation certificate\\…'
complete -c sq-revoke-subkey -l notation -d 'Adds a notation to the certification'
complete -c sq-revoke-subkey -s B -l binary -d 'Emits binary data'
complete -c sq-revoke-subkey -s h -l help -d 'Print help information'

