# sq-sign
# Autogenerated from man page /usr/share/man/man1/sq-sign.1.gz
complete -c sq-sign -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-sign -s B -l binary -d 'Emits binary data'
complete -c sq-sign -l private-key-store -d 'Provides parameters for private key store'
complete -c sq-sign -l detached -d 'Creates a detached signature'
complete -c sq-sign -l cleartext-signature -d 'Creates a cleartext signature'
complete -c sq-sign -s a -l append -d 'Appends a signature to existing signature'
complete -c sq-sign -s n -l notarize -d 'Signs a message and all existing signatures'
complete -c sq-sign -l merge -d 'Merges signatures from the input and SIGNED-MESSAGE'
complete -c sq-sign -l signer-key -d 'Signs using KEY'
complete -c sq-sign -s t -l time -d 'Chooses keys valid at the specified time and sets the signature\\*(Aqs creatio…'
complete -c sq-sign -l notation -d 'Adds a notation to the certification'
complete -c sq-sign -s h -l help -d 'Print help information'

