# sq-verify
# Autogenerated from man page /usr/share/man/man1/sq-verify.1.gz
complete -c sq-verify -s o -l output -d 'Writes to FILE or stdout if omitted'
complete -c sq-verify -l detached -d 'Verifies a detached signature'
complete -c sq-verify -s n -l signatures -d 'Sets the threshold of valid signatures to N'
complete -c sq-verify -l signer-cert -d 'Verifies signatures with CERT'
complete -c sq-verify -s h -l help -d 'Print help information'

