# sq-wkd-generate
# Autogenerated from man page /usr/share/man/man1/sq-wkd-generate.1.gz
complete -c sq-wkd-generate -s d -l direct-method -d 'Uses the direct method [default: advanced method]'
complete -c sq-wkd-generate -s s -l skip -d 'Skips certificates that do not have User IDs for given domain'
complete -c sq-wkd-generate -s h -l help -d 'Print help information'

