# sq-wkd
# Autogenerated from man page /usr/share/man/man1/sq-wkd.1.gz
complete -c sq-wkd -s n -l network-policy -d 'Sets the network policy to use'
complete -c sq-wkd -s h -l help -d 'Print help information SUBCOMMANDS'

