# sq
# Autogenerated from man page /usr/share/man/man1/sq.1.gz
complete -c sq -s h -l help -d 'Print help information'
complete -c sq -s V -l version -d 'Print version information'
complete -c sq -s f -l force -d 'Overwrites existing files'
complete -c sq -l known-notation -d 'Adds NOTATION to the list of known notations'

