# tape
# Autogenerated from man page /usr/share/man/man1/tape.1.gz
complete -c tape -s r -d 'load one or more modules before running any tests'
complete -c tape -s i -d 'ignore tests from certain folders and/or files are not intended to be run'
complete -c tape -l no-only -d 'This is particularly useful in a CI environment where an "only test" is not s…'

